module Utils_visiona

  def writeFile(filename, data)

    # i'm expecting an array of binary data array
    raise ArgumentError, "Data is not a Hash" unless data.is_a?(Hash)

    data.each do |key, value|
      data[key] = value.pduPayload.data
    end

    begin
      File.open(filename, 'wb+') do |file|
        IO.binwrite(file, data.sort.to_h.values.flatten.pack('c*'))
      end
    rescue Exception => err
      file = Tempfile.new('cfdp')
      IO.binwrite(file, data.sort.to_h.values.flatten.pack('c*'))
      file.close
      puts err
      puts "Error while writing file. It has been saved in /tmp with basename 'cfdp'"
    end
  end

  def OS_print(errorCode, string)

    if DEBUG==1
      outputStr = ""
      errorCodeHash = {0=>"ERROR", 1=>"WARNING", 2=>"SUCCESS"}
      outputStr << errorCodeHash[errorCode] << ": " << string << "\nGenerated by " << caller_locations(1,1).to_s << "\n\n"
      #puts outputStr
    end
  end
end